[project]
name = "rai-polybo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nuinashco", email = "ivan.havlytskyi@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "marimo>=0.25.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "scipy>=1.18.1",
]

[project.scripts]
rai-polybo = "rai_polybo:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
